CREATE TABLE IF NOT EXISTS quote
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    isin     VARCHAR(12) NOT NULL,
    bid      DECIMAL(19, 2),
    ask      DECIMAL(19, 2),
    bid_size BIGINT,
    ask_size BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS energy_level
(
    isin VARCHAR(12)    NOT NULL,
    elvl DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (isin)
);
